### ISSUE TITLE
nightly is broken on Linux and Mac

### ISSUE THREAD

**Issue by amtoine** [nushell/nightly#15]
looking at [this line in the latest *nightly* action](https://github.com/nushell/nightly/actions/runs/6964563750/job/18951990649#step:7:360), it looks like the cross-compilation did not run well :open_mouth: 

the result is that all build files apart from `LICENSE` could not get copied to the tarballs and thus they end up [empty](https://github.com/nushell/nightly/releases/tag/nightly-6cfe35e) :cry: 

@hustcer 
could you have a look when you get a moment? :innocent:

**Comment by hustcer** [comment]
OK, thanks for report

**Comment by hustcer** [comment]
I have delete all the bad releases, this issue should be fixed by https://github.com/nushell/nushell/pull/11146.
Let's wait and see.

**Comment by amtoine** [comment]
amazing, thanks :pray: 

my `nightly update` alias works like a charm now :relieved:
